spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
    mongodb:
      uri: ${MONGODB_URI}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        database-platform: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
        format_sql: true

oauth:
  kakao:
    base-url: https://kauth.kakao.com
    app-key: ${KAKAO_APP_KEY}
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-url: ${KAKAO_REDIRECT_URL}
  apple:
    base-url: ${APPLE_BASE_URL}
    app-key: ${APPLE_APP_KEY}
    client-id: ${APPLE_CLIENT_ID}
    client-secret: ${APPLE_CLIENT_SECRET}
    redirect-url: ${APPLE_REDIRECT_URL}
fcm:
  key:
    path: firebase-adminsdk.json
    scope: https://www.googleapis.com/auth/cloud-platform
  api:
    url: https://fcm.googleapis.com/v1/projects/${FCM_PROJECT_ID}/messages:send

token:
  secret: ${SECRET_KEY}

logging:
  level:
    root: INFO #DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework: DEBUG
#    com.example: DEBUG
